name: pubg_companion
description: Companion app for the PUBG game.

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.0
  twitter: ^0.5.2
  url_launcher: ^3.0.0
  transparent_image: ^0.1.0
  http: ^0.11.3+16

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  assets:
    # Weapons
    - assets/images/weapons/AKM.png
    - assets/images/weapons/AUG_A3.png
    - assets/images/weapons/AWM.png
    - assets/images/weapons/Crossbow.png
    - assets/images/weapons/Crowbar.png
    - assets/images/weapons/DP-28.png
    - assets/images/weapons/Groza.png
    - assets/images/weapons/Kar98k.png
    - assets/images/weapons/M16A4.png
    - assets/images/weapons/M24.png
    - assets/images/weapons/M249.png
    - assets/images/weapons/M416.png
    - assets/images/weapons/Machete.png
    - assets/images/weapons/Mini_14.png
    - assets/images/weapons/MK14.png
    - assets/images/weapons/P18C.png
    - assets/images/weapons/P92.png
    - assets/images/weapons/P1911.png
    - assets/images/weapons/Pan.png
    - assets/images/weapons/Punch.png
    - assets/images/weapons/R45.png
    - assets/images/weapons/R1895.png
    - assets/images/weapons/S12K.png
    - assets/images/weapons/S686.png
    - assets/images/weapons/S1897.png
    - assets/images/weapons/Sawed_Off.png
    - assets/images/weapons/SCAR-L.png
    - assets/images/weapons/Sickle.png
    - assets/images/weapons/SKS.png
    - assets/images/weapons/SLR.png
    - assets/images/weapons/Superman_Punch.png
    - assets/images/weapons/Tommy_Gun.png
    - assets/images/weapons/UMP9.png
    - assets/images/weapons/UZI.png
    - assets/images/weapons/Vector.png
    - assets/images/weapons/VSS.png
    - assets/images/weapons/Win94.png
    # Ammo
    - assets/images/ammo/9mm.png
    - assets/images/ammo/12_Gauge.png
    - assets/images/ammo/45_ACP.png
    - assets/images/ammo/300_Magnum.png
    - assets/images/ammo/556mm.png
    - assets/images/ammo/762mm.png
    - assets/images/ammo/Bolt.png
    # Flags
    - assets/images/flags/ussr.png
    - assets/images/flags/nazi.png
    # UI
    - assets/images/ui/header_row.png
    - assets/images/ui/header_row_alt.png
    - assets/images/ui/gamepedia_logo.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies, 
  # see https://flutter.io/custom-fonts/#from-packages

  fonts:
    - family: Assistant
      fonts:
            - asset: assets/fonts/Assistant/Assistant-ExtraLight.ttf
              weight: 200
            - asset: assets/fonts/Assistant/Assistant-Light.ttf
              weight: 300
            - asset: assets/fonts/Assistant/Assistant-Regular.ttf
              weight: 400
            - asset: assets/fonts/Assistant/Assistant-SemiBold.ttf
              weight: 600
            - asset: assets/fonts/Assistant/Assistant-Bold.ttf
              weight: 700
            - asset: assets/fonts/Assistant/Assistant-ExtraBold.ttf
              weight: 800
    - family: Teko
      fonts:
        - asset: assets/fonts/Teko/Teko-Light.ttf
          weight: 300
        - asset: assets/fonts/Teko/Teko-Regular.ttf
          weight: 400
        - asset: assets/fonts/Teko/Teko-Medium.ttf
          weight: 500
        - asset: assets/fonts/Teko/Teko-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Teko/Teko-Bold.ttf
          weight: 700
    - family: HeadlinerNo45
      fonts:
      - asset: assets/fonts/HeadlinerNo45/HeadlinerNo45.ttf
    - family: FontAwesomeRegular
      fonts:
        - asset: assets/fonts/FontAwesome/fa-regular-400.ttf
          weight: 400
    - family: FontAwesomeSolid
      fonts:
        - asset: assets/fonts/FontAwesome/fa-solid-900.ttf
          weight: 900
    - family: FontAwesomeLight
      fonts:
        - asset: assets/fonts/FontAwesome/fa-light-300.ttf
          weight: 300
    - family: FontAwesomeBrands
      fonts:
        - asset: assets/fonts/FontAwesome/fa-brands-400.ttf
          weight: 400
    - family: GovIcons
      fonts:
        - asset: assets/fonts/GovIcons/govicons-webfont.ttf